### ISSUE TITLE
Input fields of past matches have smaller width than future matches on mobile

### ISSUE THREAD

**Issue by theogom** [chomeirb/fofoprono-client#29]

**Comment by theogom** [comment]
![Image](https://user-images.githubusercontent.com/62011427/203878751-840b1277-e2e4-48c0-8f9d-9419a3604102.png)

**Comment by Canleskis** [comment]
Je compte régler en même temps que https://github.com/chomeirb/fofoprono-client/issues/20 en améliorant l'affichage de manière générale
